[2016-09-09 08:57:09,104] ERROR [play-thread-1] com.aton.base.secure.Secure.checkAuthentication(Secure.java:92) - Login admin not exists,admin_id=null
[2016-09-09 09:25:24,529] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: [type] Required
[2016-09-09 09:52:19,499] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71be0f123
Internal Server Error (500) for request GET /buyer/task2/6587

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 225)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform2 for class: vos.BuyerTaskVo2 Possible solutions: platform.

play.exceptions.TemplateExecutionException: No such property: platform2 for class: vos.BuyerTaskVo2
Possible solutions: platform
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1713)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform2 for class: vos.BuyerTaskVo2
Possible solutions: platform
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-09-09 09:52:24,444] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71be0f124
Internal Server Error (500) for request GET /buyer/task2/6587

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 225)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform2 for class: vos.BuyerTaskVo2 Possible solutions: platform.

play.exceptions.TemplateExecutionException: No such property: platform2 for class: vos.BuyerTaskVo2
Possible solutions: platform
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1713)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform2 for class: vos.BuyerTaskVo2
Possible solutions: platform
	at /app/views/TaskCenter/buyerTaskDetail2.html.(line:225)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-09-09 10:49:43,749] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71be0f125
Internal Server Error (500) for request GET /buyer/tasks2

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	... 1 more
[2016-09-09 10:49:43,749] ERROR [play-thread-1] play.Logger.error(Logger.java:457) - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:45)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:381)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:377)
	at sun.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:95)
	at sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:313)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1322)
	at java.io.ObjectStreamClass.access$1500(ObjectStreamClass.java:50)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:435)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:411)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:308)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:545)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1580)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1493)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1729)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1326)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:348)
	at java.util.HashMap.readObject(HashMap.java:1029)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1756)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1326)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:348)
	at play.utils.Java.deserialize(Java.java:361)
	at play.templates.GroovyTemplate.directLoad(GroovyTemplate.java:87)
	at play.templates.BaseTemplate.loadFromCache(BaseTemplate.java:56)
[2016-09-09 11:23:03,494] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 11:23:03,494] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy54.selectByPlatform(Unknown Source)
	at models.Shop3.findByPlatformAndSellerId(Shop3.java:84)
	at controllers.UserCenter.listShops3(UserCenter.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 33 more
[2016-09-09 11:23:09,819] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 11:23:09,819] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy54.selectByPlatform(Unknown Source)
	at models.Shop3.findByPlatformAndSellerId(Shop3.java:84)
	at controllers.UserCenter.listShops3(UserCenter.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 33 more
[2016-09-09 11:28:54,477] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: [] Required
[2016-09-09 11:39:59,451] ERROR [jobs-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71beeifab
Error during job execution (jobs.TaskKeeper2)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:47)
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:52)
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:49)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at jobs.TaskKeeper2.doJob(TaskKeeper2.java:54)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	... 1 more
[2016-09-09 11:40:59,007] ERROR [jobs-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71beeifad
Error during job execution (jobs.TaskKeeper)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:47)
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:52)
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:49)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at jobs.TaskKeeper.doJob(TaskKeeper.java:51)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	... 1 more
[2016-09-09 11:41:00,423] ERROR [jobs-thread-2] play.Logger.niceThrowable(Logger.java:604) - 

@71beeifaf
Error during job execution (jobs.TaskKeeper2)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:47)
	at org.apache.ibatis.binding.MapperProxyFactory.newInstance(MapperProxyFactory.java:52)
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:49)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at jobs.TaskKeeper2.doJob(TaskKeeper2.java:54)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	... 1 more
[2016-09-09 11:53:32,046] ERROR [jobs-thread-2] play.Logger.niceThrowable(Logger.java:604) - 

@71beeifah
Error during job execution (jobs.AddKwdForFlow)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-09-09 11:54:07,052] ERROR [jobs-thread-4]  - 

@71beeifaj
Error during job execution (jobs.GetExpressNo)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-09-09 11:54:14,283] ERROR [jobs-thread-7]  - Oops. Error in Logger !
java.lang.OutOfMemoryError: PermGen space
[2016-09-09 12:10:08,746] ERROR [jobs-thread-9]  - Oops. Error in Logger !
java.lang.OutOfMemoryError: PermGen space
[2016-09-09 13:49:28,654] ERROR [play-thread-1]  - Oops. Error in Logger !
java.lang.OutOfMemoryError: PermGen space
[2016-09-09 13:49:29,800] ERROR [play-thread-1]  - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-09-09 13:52:14,663] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 13:52:14,663] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
java.lang.NullPointerException
	at controllers.UserCenter.shopDetail2(UserCenter.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 13:52:23,753] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 13:52:23,753] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
java.lang.NullPointerException
	at controllers.UserCenter.shopDetail2(UserCenter.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 13:52:28,335] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 13:52:28,335] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
java.lang.NullPointerException
	at controllers.UserCenter.shopDetail2(UserCenter.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 13:55:06,879] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 13:55:06,879] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
java.lang.NullPointerException
	at controllers.UserCenter.shopDetail2(UserCenter.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 13:55:29,746] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: [branch] Required
[2016-09-09 13:58:04,335] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: [branch] Required
[2016-09-09 14:11:04,677] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bf8e9a3
Internal Server Error (500) for request GET /buyer/task/6591

Execution exception (In /app/models/BuyerTask.java around line 1095)
NullPointerException occured : Try to read buyerId on null object vos.BuyerTaskVo (models.BuyerTask.findDetail, line 1095)

play.exceptions.JavaExecutionException: Try to read buyerId on null object vos.BuyerTaskVo (models.BuyerTask.findDetail, line 1095)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Try to read buyerId on null object vos.BuyerTaskVo (models.BuyerTask.findDetail, line 1095)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.BuyerTask.findDetail(BuyerTask.java:1095)
	at controllers.TaskCenter.buyerTaskDetail(TaskCenter.java:1619)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
[2016-09-09 14:23:51,648] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bf8e9a4
Internal Server Error (500) for request GET /buyer/task2/6591

Template compilation error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 402)
The template /app/views/TaskCenter/buyerTaskDetail2.html does not compile : #{/if} is not opened.

play.exceptions.TemplateCompilationException: #{/if} is not opened.
	at play.templates.GroovyTemplateCompiler.endTag(GroovyTemplateCompiler.java:326)
	at play.templates.TemplateCompiler.generate(TemplateCompiler.java:93)
	at play.templates.TemplateCompiler.compile(TemplateCompiler.java:15)
	at play.templates.GroovyTemplateCompiler.compile(GroovyTemplateCompiler.java:42)
	at play.templates.TemplateCompiler.compile(TemplateCompiler.java:28)
	at play.templates.TemplateLoader.load(TemplateLoader.java:89)
	at play.templates.TemplateLoader.load(TemplateLoader.java:179)
	at play.mvc.Controller.renderTemplate(Controller.java:675)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1724)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
[2016-09-09 14:58:12,185] ERROR [play-thread-1] com.aton.base.secure.Secure.checkAuthentication(Secure.java:92) - Login admin not exists,admin_id=null
[2016-09-09 15:09:31,440] ERROR [jobs-thread-6] play.Logger.niceThrowable(Logger.java:604) - 

@71bfg5n03
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskCenter.java around line 1720)
The file /app/controllers/TaskCenter.java could not be compiled. Error raised is : The method get(int) is undefined for the type BuyerTaskStep2

play.exceptions.CompilationException: The method get(int) is undefined for the type BuyerTaskStep2
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 15:09:31,653] ERROR [jobs-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bfg5n05
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/TaskCenter.java around line 1720)
The file /app/controllers/TaskCenter.java could not be compiled. Error raised is : The method get(int) is undefined for the type BuyerTaskStep2

play.exceptions.CompilationException: The method get(int) is undefined for the type BuyerTaskStep2
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 15:11:08,397] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bfg5n07
Internal Server Error (500) for request GET /buyer/task2/6592

Execution exception (In /app/models/Task.java around line 876)
NullPointerException occured : Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)

play.exceptions.JavaExecutionException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at models.BuyerTaskStep2.findByTaskIdForSysRefund(BuyerTaskStep2.java:194)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1717)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
[2016-09-09 15:12:19,044] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bfg5n08
Internal Server Error (500) for request GET /buyer/task2/6592

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	... 1 more
[2016-09-09 15:12:19,044] ERROR [play-thread-1] play.Logger.error(Logger.java:457) - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.templates.GroovyTemplate$TClassLoader.defineTemplate(GroovyTemplate.java:79)
	at play.templates.GroovyTemplate.directLoad(GroovyTemplate.java:92)
	at play.templates.BaseTemplate.loadFromCache(BaseTemplate.java:56)
	at play.templates.TemplateLoader.load(TemplateLoader.java:81)
	at play.templates.TemplateLoader.load(TemplateLoader.java:179)
	at play.server.PlayHandler.serve500(PlayHandler.java:792)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 15:43:13,195] ERROR [play-thread-1] com.aton.base.secure.Secure.checkAuthentication(Secure.java:92) - Login admin not exists,admin_id=null
[2016-09-09 16:19:29,771] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 16:19:29,771] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy38.selectByPlatform(Unknown Source)
	at models.Shop3.findByPlatformAndSellerId(Shop3.java:84)
	at controllers.UserCenter.listShops3(UserCenter.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 33 more
[2016-09-09 16:19:42,674] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 16:19:42,674] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
### The error may exist in models/mappers/ShopMapper3.java (best guess)
### The error may involve models.mappers.ShopMapper3.selectByPlatform-Inline
### The error occurred while setting parameters
### SQL: select * from shop3 where platform=? and seller_id=?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy38.selectByPlatform(Unknown Source)
	at models.Shop3.findByPlatformAndSellerId(Shop3.java:84)
	at controllers.UserCenter.listShops3(UserCenter.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.shop3' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 33 more
[2016-09-09 16:43:28,797] ERROR [jobs-thread-2] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg7n
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/UserCenter.java around line 1039)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : Duplicate method buyerAccount() in type UserCenter

play.exceptions.CompilationException: Duplicate method buyerAccount() in type UserCenter
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:43:28,979] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg7p
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/UserCenter.java around line 1039)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : Duplicate method buyerAccount() in type UserCenter

play.exceptions.CompilationException: Duplicate method buyerAccount() in type UserCenter
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:46:05,913] ERROR [jobs-thread-7] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg81
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/UserCenter.java around line 1303)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : Incompatible operand types Platform3 and Platform

play.exceptions.CompilationException: Incompatible operand types Platform3 and Platform
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:46:06,094] ERROR [jobs-thread-6] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg83
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/UserCenter.java around line 1303)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : Incompatible operand types Platform3 and Platform

play.exceptions.CompilationException: Incompatible operand types Platform3 and Platform
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:54:03,416] ERROR [jobs-thread-2] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg85
Error during job execution (jobs.AddKwdForFlow)

Compilation error (In /app/controllers/UserCenter.java around line 1298)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)

play.exceptions.CompilationException: The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:54:06,017] ERROR [jobs-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg87
Error during job execution (jobs.BuyerTaskCancel)

Compilation error (In /app/controllers/UserCenter.java around line 1298)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)

play.exceptions.CompilationException: The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:428)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 16:54:06,174] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@71bg2eg89
Error during job execution (jobs.GetExpressNo)

Compilation error (In /app/controllers/UserCenter.java around line 1298)
The file /app/controllers/UserCenter.java could not be compiled. Error raised is : The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)

play.exceptions.CompilationException: The method findForTakingTask(BuyerAccountSearchVo) in the type BuyerAccount is not applicable for the arguments (BuyerAccountSearchVo3)
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-09 17:10:41,129] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 17:10:41,129] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
org.apache.ibatis.binding.BindingException: Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:47)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at models.BuyerAccount3.findList(BuyerAccount3.java:116)
	at controllers.UserCenter.listBuyerAccounts3(UserCenter.java:1299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 17:12:33,184] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bg69mji
Error during job execution (jobs.Bootstrap)

Oops: ExceptionInInitializerError
An unexpected error occured caused by exception ExceptionInInitializerError: null

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.ExceptionInInitializerError
	at models.SysConfig.initCache(SysConfig.java:139)
	at jobs.Bootstrap.doJob(Bootstrap.java:26)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	... 1 more
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error building SqlSession.
### The error may exist in models/mappers/BuyerAccountMapper3.xml
### The error occurred while processing mapper_resultMap[BaseResultMap]
### Cause: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:54)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:38)
	at com.aton.db.SessionFactory.<init>(SessionFactory.java:44)
	at com.aton.db.SessionFactory.<clinit>(SessionFactory.java:31)
	... 10 more
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:109)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parse(XMLConfigBuilder.java:92)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:52)
	... 13 more
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:164)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:71)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:651)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.mapperElement(XMLConfigBuilder.java:330)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:107)
	... 15 more
Caused by: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.MapperBuilderAssistant.setCurrentNamespace(MapperBuilderAssistant.java:78)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:112)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:164)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:71)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:651)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.mapperElement(XMLConfigBuilder.java:330)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:107)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parse(XMLConfigBuilder.java:92)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:52)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:38)
	at com.aton.db.SessionFactory.<init>(SessionFactory.java:44)
	at com.aton.db.SessionFactory.<clinit>(SessionFactory.java:31)
	at models.SysConfig.initCache(SysConfig.java:139)
	at jobs.Bootstrap.doJob(Bootstrap.java:26)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	at play.jobs.Job.run(Job.java:170)
	at play.jobs.JobsPlugin.afterApplicationStart(JobsPlugin.java:116)
	at play.plugins.PluginCollection.afterApplicationStart(PluginCollection.java:521)
	at play.Play.start(Play.java:558)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.server.PlayHandler$NettyInvocation.init(PlayHandler.java:205)
	at play.Invoker$Invocation.run(Invoker.java:284)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 17:12:34,048] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71bg69mjj
Internal Server Error (500) for request GET /buyer/account3

Oops: ExceptionInInitializerError
An unexpected error occured caused by exception ExceptionInInitializerError: null

play.exceptions.UnexpectedException: Unexpected Error
	at play.jobs.Job.onException(Job.java:157)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.ExceptionInInitializerError
	at models.SysConfig.initCache(SysConfig.java:139)
	at jobs.Bootstrap.doJob(Bootstrap.java:26)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	... 1 more
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error building SqlSession.
### The error may exist in models/mappers/BuyerAccountMapper3.xml
### The error occurred while processing mapper_resultMap[BaseResultMap]
### Cause: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:54)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:38)
	at com.aton.db.SessionFactory.<init>(SessionFactory.java:44)
	at com.aton.db.SessionFactory.<clinit>(SessionFactory.java:31)
	... 10 more
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:109)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parse(XMLConfigBuilder.java:92)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:52)
	... 13 more
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:164)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:71)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:651)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.mapperElement(XMLConfigBuilder.java:330)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:107)
	... 15 more
Caused by: org.apache.ibatis.builder.BuilderException: Wrong namespace. Expected 'models.mappers.BuyerAccountMapper3' but found 'models.mappers.BuyerAccountMapper'.
	at org.apache.ibatis.builder.MapperBuilderAssistant.setCurrentNamespace(MapperBuilderAssistant.java:78)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:112)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:164)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:71)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:651)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.mapperElement(XMLConfigBuilder.java:330)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parseConfiguration(XMLConfigBuilder.java:107)
	at org.apache.ibatis.builder.xml.XMLConfigBuilder.parse(XMLConfigBuilder.java:92)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:52)
	at org.apache.ibatis.session.SqlSessionFactoryBuilder.build(SqlSessionFactoryBuilder.java:38)
	at com.aton.db.SessionFactory.<init>(SessionFactory.java:44)
	at com.aton.db.SessionFactory.<clinit>(SessionFactory.java:31)
	at models.SysConfig.initCache(SysConfig.java:139)
	at jobs.Bootstrap.doJob(Bootstrap.java:26)
	at play.jobs.Job.doJobWithResult(Job.java:54)
	at play.jobs.Job$2.apply(Job.java:199)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.jobs.Job.withinFilter(Job.java:176)
	at play.jobs.Job.call(Job.java:196)
	at play.jobs.Job.run(Job.java:170)
	at play.jobs.JobsPlugin.afterApplicationStart(JobsPlugin.java:116)
	at play.plugins.PluginCollection.afterApplicationStart(PluginCollection.java:521)
	at play.Play.start(Play.java:558)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.server.PlayHandler$NettyInvocation.init(PlayHandler.java:205)
	at play.Invoker$Invocation.run(Invoker.java:284)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 17:14:28,283] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 17:14:28,284] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
org.apache.ibatis.binding.BindingException: Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:47)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at models.BuyerAccount3.findList(BuyerAccount3.java:116)
	at controllers.UserCenter.listBuyerAccounts3(UserCenter.java:1299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 17:15:02,364] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 17:15:02,365] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
org.apache.ibatis.binding.BindingException: Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:47)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at models.BuyerAccount3.findList(BuyerAccount3.java:116)
	at controllers.UserCenter.listBuyerAccounts3(UserCenter.java:1299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-09-09 17:17:22,238] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-09-09 17:17:22,238] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
org.apache.ibatis.binding.BindingException: Type interface models.mappers.BuyerAccountMapper3 is not known to the MapperRegistry.
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:47)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:655)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:222)
	at models.BuyerAccount3.findList(BuyerAccount3.java:116)
	at controllers.UserCenter.listBuyerAccounts3(UserCenter.java:1299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
